package pomodoro.timer;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author dogukan
 */
public class PomodoroMain extends javax.swing.JFrame implements ActionListener{

    public PomodoroMain() {
        initComponents();
        initFrame();
        initTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pomodoroButton = new javax.swing.JLabel();
        shortBreakButton = new javax.swing.JLabel();
        longBreakButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        startButton = new javax.swing.JLabel();
        stopButton = new javax.swing.JLabel();
        resetButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pomodoroButton.setBackground(new java.awt.Color(255, 51, 51));
        pomodoroButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        pomodoroButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pomodoroButton.setText("Pomodoro");
        pomodoroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pomodoroButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pomodoroButton.setOpaque(true);
        pomodoroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pomodoroButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pomodoroButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pomodoroButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
        jPanel1.add(pomodoroButton, gridBagConstraints);

        shortBreakButton.setBackground(new java.awt.Color(255, 51, 51));
        shortBreakButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shortBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        shortBreakButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shortBreakButton.setText("Short Break");
        shortBreakButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shortBreakButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shortBreakButton.setOpaque(true);
        shortBreakButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shortBreakButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shortBreakButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shortBreakButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 12, 11);
        jPanel1.add(shortBreakButton, gridBagConstraints);

        longBreakButton.setBackground(new java.awt.Color(255, 51, 51));
        longBreakButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        longBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        longBreakButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        longBreakButton.setText("Long Break");
        longBreakButton.setToolTipText("");
        longBreakButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        longBreakButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        longBreakButton.setInheritsPopupMenu(false);
        longBreakButton.setOpaque(true);
        longBreakButton.setVerifyInputWhenFocusTarget(false);
        longBreakButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                longBreakButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                longBreakButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                longBreakButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
        jPanel1.add(longBreakButton, gridBagConstraints);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 60));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Effective Study");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        time.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("25:00");
        time.setPreferredSize(new java.awt.Dimension(89, 14));
        time.setRequestFocusEnabled(false);
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 170, 89));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        startButton.setBackground(new java.awt.Color(255, 51, 51));
        startButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startButton.setText("Start");
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.setOpaque(true);
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.insets = new java.awt.Insets(9, 19, 11, 27);
        jPanel3.add(startButton, gridBagConstraints);

        stopButton.setBackground(new java.awt.Color(255, 51, 51));
        stopButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stopButton.setForeground(new java.awt.Color(255, 255, 255));
        stopButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopButton.setText("Stop");
        stopButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stopButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopButton.setOpaque(true);
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stopButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stopButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.insets = new java.awt.Insets(9, 19, 11, 27);
        jPanel3.add(stopButton, gridBagConstraints);

        resetButton.setBackground(new java.awt.Color(255, 51, 51));
        resetButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetButton.setText("Reset");
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetButton.setOpaque(true);
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.insets = new java.awt.Insets(9, 19, 11, 27);
        jPanel3.add(resetButton, gridBagConstraints);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 500, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initFrame() {
        ImageIcon icon = new ImageIcon("src/res/icon.png");
        this.setIconImage(icon.getImage());
        this.setTitle("Tomato Timer");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    private void pomodoroButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomodoroButtonMouseEntered
        pomodoroButton.setBackground( new Color(255,102,102) );
    }//GEN-LAST:event_pomodoroButtonMouseEntered

    private void pomodoroButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomodoroButtonMouseExited
        pomodoroButton.setBackground( new Color(255,51,51) );
    }//GEN-LAST:event_pomodoroButtonMouseExited

    private void shortBreakButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortBreakButtonMouseEntered
        shortBreakButton.setBackground( new Color(255,102,102) );
    }//GEN-LAST:event_shortBreakButtonMouseEntered

    private void shortBreakButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortBreakButtonMouseExited
        shortBreakButton.setBackground( new Color(255,51,51) );
    }//GEN-LAST:event_shortBreakButtonMouseExited

    private void longBreakButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_longBreakButtonMouseEntered
        longBreakButton.setBackground( new Color(255,102,102) );
    }//GEN-LAST:event_longBreakButtonMouseEntered

    private void longBreakButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_longBreakButtonMouseExited
        longBreakButton.setBackground( new Color(255,51,51) );
    }//GEN-LAST:event_longBreakButtonMouseExited

    private void startButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseEntered
        startButton.setBackground( new Color(255,102,102) );
    }//GEN-LAST:event_startButtonMouseEntered

    private void resetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseEntered
        resetButton.setBackground( new Color(255,102,102) );
    }//GEN-LAST:event_resetButtonMouseEntered

    private void resetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseExited
        resetButton.setBackground( new Color(255,51,51) );
    }//GEN-LAST:event_resetButtonMouseExited

    private void stopButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseEntered
        stopButton.setBackground( new Color(255,102,102) );
    }//GEN-LAST:event_stopButtonMouseEntered

    private void stopButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseExited
        stopButton.setBackground( new Color(255,51,51) );
    }//GEN-LAST:event_stopButtonMouseExited

    private void startButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseExited
        startButton.setBackground( new Color(255,51,51) );
    }//GEN-LAST:event_startButtonMouseExited

    private void pomodoroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomodoroButtonMouseClicked
        time.setText("25:00");
        currentTimer = TimerState.Pomodoro;
        if ( timer.isRunning() )
            timer.stop();
    }//GEN-LAST:event_pomodoroButtonMouseClicked

    private void shortBreakButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortBreakButtonMouseClicked
        time.setText("5:00");
        currentTimer = TimerState.ShortBreak;
        if ( timer.isRunning() )
            timer.stop();        
    }//GEN-LAST:event_shortBreakButtonMouseClicked

    private void longBreakButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_longBreakButtonMouseClicked
        time.setText("10:00");
        currentTimer = TimerState.LongBreak;
        if ( timer.isRunning() )
            timer.stop();        
    }//GEN-LAST:event_longBreakButtonMouseClicked

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        timer.start();
    }//GEN-LAST:event_startButtonMouseClicked

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        if ( currentTimer == TimerState.Pomodoro )
            time.setText("25:00");
        else if ( currentTimer == TimerState.ShortBreak )
            time.setText("5:00");
        else 
            time.setText("10:00");
        
        if ( timer.isRunning() )
            timer.stop();
    }//GEN-LAST:event_resetButtonMouseClicked

    private void stopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseClicked
        timer.stop();
    }//GEN-LAST:event_stopButtonMouseClicked


    
    
    private static final int DELAY = 1000;
    private TimerState currentTimer = TimerState.Pomodoro;
    private Timer timer;
    
    private void initTimer() {
        timer = new Timer(DELAY,this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        String[] countdown = time.getText().split(":");
        int min = Integer.parseInt(countdown[0]);
        int sec = Integer.parseInt(countdown[1]);
        
        if ( min == 0 && sec == 0 ) {
            timer.stop();
            playBuzzer();
        }
        else if ( sec != 0 )
            sec--;
        else {
            min--;
            sec = 59;
        }
        
        if ( min < 10 && sec < 10 )
            time.setText("0"+min+":0"+sec);
        else if ( min < 10 )
            time.setText("0"+min+":"+sec);
        else if ( sec < 10 ) 
            time.setText(min+":0"+sec);
        else 
            time.setText(min+":"+sec);
    }
    
    private void playBuzzer() {
        String gongFile = "src/res/buzzer.wav";
        InputStream in = null;
        try {
            in = new FileInputStream(gongFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PomodoroMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        // create an audiostream from the inputstream
        AudioStream audioStream = null;
        try {
            audioStream = new AudioStream(in);
        } catch (IOException ex) {
            Logger.getLogger(PomodoroMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        // play the audio clip with the audioplayer class
        AudioPlayer.player.start(audioStream);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel longBreakButton;
    private javax.swing.JLabel pomodoroButton;
    private javax.swing.JLabel resetButton;
    private javax.swing.JLabel shortBreakButton;
    private javax.swing.JLabel startButton;
    private javax.swing.JLabel stopButton;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PomodoroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PomodoroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PomodoroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PomodoroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PomodoroMain().setVisible(true);
            }
        });
    }



}
